### ISSUE TITLE
Config not syncing/working when in multiplayer

### ISSUE THREAD

**Issue by ZigzagAwaka** [Inoyuuuuu/GiantExtensionLaddersV2#5] opened 2024-05-20 16:46 UTC
When playing with multiple players, config are not sync with the host but instead they are reseted to their default state

For example, I disable big and huge ladders, i share a profile code with other players so they have the same config, someone starts the game and everyone joins, but big and huge ladders are still in the shop
This could be a Csync related issue, and in that case you can try switching to Sigurd's Csync if you want, otherwise idk

**Comment by Inoyuuuuu** [comment] 2024-05-20 20:43
Config syncing works fine at my end, but I think I do know what the problem is!
In my recent 2.3.0 update I changed the mod's GUID (basically the mod's unique name) from "GiantExtensionLadders" to "inoyu.GiantExtensionLadders". If you edit the "GiantExtensionLadders.cfg" file, nothing will change, because the mod now uses the "inoyu.GiantExtensionLadders.cfg" file as configs (if not there, this config file will be created after the first launch with my mod active). To avoid confusion, you can simply delete the old "GiantExtensionLadders.cfg" file.

However, **if this is not the issue**, please send me a list of your mods and the LogOutput.txt file located in "C:\Users\your_user_name\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\your_profile_name\BepInEx", after you tried to sync the configs.

Please let me know if this worked for you!

**Comment by ZigzagAwaka** [comment] 2024-05-21 16:53
I can't confirm if this issue is from the 2.3.0 version of the mod because I was using 2.2.0 and previous version for a very long time
Unfortunatly, i am not able to share the log file bc I disabled it in BepinEx configs, but this is the profile i used 018f9231-26a4-3368-d4e6-d7f55bf78650

In the profile, GiantExtensionLadders should be on the last version bc i updated the mod (and configs). Like i said before, i didn't checked if this is still happening on the last version

**Comment by ZigzagAwaka** [comment] 2024-05-21 16:55
I will get back to you concerning the latest version

**Comment by Inoyuuuuu** [comment] 2024-05-23 14:25
Hey, so I got the code and the configs seem to be fine (big and huge ladder disabled in configs and the same when I load into a game). Since you shared a code with your friends, it would be good to know, what exactly occured. When in game, did they all have the same configs (the default ones) or did just one had them? Did the host maybe delete theirs? 
This is maybe a thunderstore client issue (you have a lot of mods too, maybe someone exited downloading the modpack too early).

I will look deeper into this as soon I am home. In 2.2.0 I updated CSync to the latest version, so this could've somehow created issues that went past the tests I did. **If this issue persists on 2.3.0, you can use versions before 2.2.0, they have some drawbacks, but should work syncing wise**.
I'd recommend you turning on the log file again btw, this can help a lot with problems like this.

Any feedback on this is much appreciated!

**Comment by ZigzagAwaka** [comment] 2024-05-23 17:08
I can confirm their was no issues when downloading the profile (this is the same profile we used since 40 mods and GiantExtensionLadders was also buggy at this time)
I'm going to test if the issue is still present on the latest version and i will get back to you in the following days

Also i'm not an expert on this but since their is 2 versions of Csync available and almost no one uses owen's anymore, this can be a good idea to switch to sigurd's (this way, players will not have 2 Csync in their profile)

**Comment by Inoyuuuuu** [comment] 2024-05-23 21:30
Thanks for testing, I hope there are no issues for you.

Regarding the CSyncs, I know the 2 CSyncs are confusing but they both being in one modpack shouldn't cause any problems. There are a few reasons why I use Owen's CSync, main one being that they work in the same way and Owen is the original dev behind CSync, his version has his support.

**Comment by Inoyuuuuu** [comment] 2024-05-24 13:01
I think I have found your problem and it is still an issue with 2.3.0. To recreate it, disable one or more ladders, start the game, join a lobby, leave after a short time and then join a new lobby. Then all ladders will be enabled since I accidentally coded the item sync to only happen once per game session. 
I still have to do some tests, but I think I fixed it.

**Comment by ZigzagAwaka** [comment] 2024-05-24 16:28
> Thanks for testing, I hope there are no issues for you.
> 
> Regarding the CSyncs, I know the 2 CSyncs are confusing but they both being in one modpack shouldn't cause any problems. There are a few reasons why I use Owen's CSync, main one being that they work in the same way and Owen is the original dev behind CSync, his version has his support.

Understandable

**Comment by ZigzagAwaka** [comment] 2024-05-24 16:29
> I think I have found your problem and it is still an issue with 2.3.0. To recreate it, disable one or more ladders, start the game, join a lobby, leave after a short time and then join a new lobby. Then all ladders will be enabled since I accidentally coded the item sync to only happen once per game session. I still have to do some tests, but I think I fixed it.

This might be the issue, i'm gonna test it

**Comment by Inoyuuuuu** [comment] 2024-05-25 01:25
updated version (2.3.2) is out with a fix for the issue I described, I hope this fixed yours too.

**Comment by ZigzagAwaka** [comment] 2024-05-25 09:50
I played yesterday with 5 players on the 2.3.1 version and the issue was not there
Im gonna test the new version today maybe

**Comment by Inoyuuuuu** [comment] 2024-05-25 12:52
Alrighty, sounds good. Thank you for testing all this on your end btw, much appreciated! I will close this issue if you come back with a good result or if you decide not to test it (up to you).

**Comment by ZigzagAwaka** [comment] 2024-05-25 23:20
Hello again, just finished a testing session, the issue is now a story of the past
Thanks for the fix

**Closed as completed** 2024-05-25 23:23 UTC
